server:
  port: 8090
spring:
  data:
    mongodb:
      username: fatmaRebai
      password: fatmaRebai
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin